<?php

namespace AppBundle\Repository;

/**
 * PresentationImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PresentationImageRepository extends \Doctrine\ORM\EntityRepository
{
}
